#!/bin/bash
#
# Builds the junixsocket website.
# 
# Copyright 2023 by Christian Kohlschütter
# SPDX-License-Identifier: Apache-2.0
#
#
set -e
dirname=$(dirname "$0")
cd "${dirname}/.."
junixsocketDir=$(pwd)

(
set -x
mvn clean && \
mvn install site -D strict -Drelease -pl '!junixsocket-native,!junixsocket-native-common,!junixsocket-native-cross' && \
mvn install site -pl junixsocket-jetty,junixsocket-selftest-native-image && \
mvn javadoc:aggregate -P '!with-non-modularized' -pl '!junixsocket-native' && \
mvn jxr:aggregate jxr:test-aggregate -Drelease && \
mvn site:stage -Drelease -pl '!junixsocket-native,!junixsocket-native-common,!junixsocket-native-cross'
) || exit $?

echo "The website should now be inspected at ${junixsocketDir}/target/staging/index.html"
if [[ $(uname) == "Darwin" ]]; then
  open "${junixsocketDir}/target/staging/index.html"
fi
